{
    "BODY": [
        [
            "ASSIGNMENT_FUNCALL", 
            "BODY_COMMA"
        ], 
        [
            "FUN", 
            "BODY_COMMA"
        ], 
        [
            "IF", 
            "BODY_COMMA"
        ], 
        [
            "WHILE", 
            "BODY_COMMA"
        ], 
        [
            "RETURN", 
            "BODY_COMMA"
        ]
    ], 
    "RETURN": [
        [
            "return", 
            ":", 
            "R"
        ]
    ], 
    "ARG_LIST_END": [
        [
            ",", 
            "ARG_LIST"
        ], 
        [
            "e"
        ]
    ], 
    "PARAM_LIST_END": [
        [
            ",", 
            "PARAM_LIST"
        ], 
        [
            "e"
        ]
    ], 
    "PARAM_LIST": [
        [
            "<var>", 
            "PARAM_LIST_END"
        ]
    ], 
    "FUN": [
        [
            "function", 
            "<var>", 
            ":", 
            "{", 
            "args", 
            ":", 
            "[", 
            "PARAM_LIST", 
            "]", 
            ",", 
            "BODY", 
            "}"
        ]
    ], 
    "VARVALEXP": [
        [
            "<var>"
        ], 
        [
            "<num>"
        ], 
        [
            "EXP"
        ]
    ], 
    "WHILE": [
        [
            "while", 
            ":", 
            "{", 
            "COND", 
            ",", 
            "BODY", 
            "}"
        ]
    ], 
    "VAR_RIGHT": [
        [
            "<var>"
        ], 
        [
            "<num>"
        ], 
        [
            "EXP"
        ], 
        [
            "[", 
            "ARG_LIST", 
            "]"
        ]
    ], 
    "IF": [
        [
            "if", 
            ":", 
            "{", 
            "COND", 
            ",", 
            "then", 
            ":", 
            "SC", 
            ",", 
            "else", 
            ":", 
            "SC", 
            "}"
        ]
    ], 
    "EXP_IN": [
        [
            "+", 
            ":", 
            "[", 
            "ARG_LIST", 
            "]"
        ], 
        [
            "-", 
            ":", 
            "[", 
            "ARG_PAIR", 
            "]"
        ], 
        [
            "*", 
            ":", 
            "[", 
            "ARG_LIST", 
            "]"
        ], 
        [
            "/", 
            ":", 
            "[", 
            "ARG_PAIR", 
            "]"
        ], 
        [
            ">", 
            ":", 
            "[", 
            "ARG_PAIR", 
            "]"
        ], 
        [
            "<", 
            ":", 
            "[", 
            "ARG_PAIR", 
            "]"
        ], 
        [
            "==", 
            ":", 
            "[", 
            "ARG_PAIR", 
            "]"
        ], 
        [
            ">=", 
            ":", 
            "[", 
            "ARG_PAIR", 
            "]"
        ], 
        [
            "<=", 
            ":", 
            "[", 
            "ARG_PAIR", 
            "]"
        ], 
        [
            "and", 
            ":", 
            "[", 
            "ARG_PAIR", 
            "]"
        ], 
        [
            "or", 
            ":", 
            "[", 
            "ARG_PAIR", 
            "]"
        ], 
        [
            "not", 
            ":", 
            "VARVALEXP"
        ], 
        [
            "ASSIGNMENT_FUNCALL"
        ]
    ], 
    "ARG_PAIR_END": [
        [
            ",", 
            "VARVALEXP"
        ]
    ], 
    "VAR_LEFT": [
        [
            "<var>", 
            ":"
        ]
    ], 
    "EXP": [
        [
            "{", 
            "EXP_IN", 
            "}"
        ]
    ], 
    "ASSIGNMENT_FUNCALL": [
        [
            "VAR_LEFT", 
            "VAR_RIGHT"
        ]
    ], 
    "SC": [
        [
            "{", 
            "BODY", 
            "}"
        ]
    ], 
    "COND": [
        [
            "VARVALEXP"
        ]
    ], 
    "R": [
        [
            "EXP"
        ], 
        [
            "<var>"
        ], 
        [
            "<num>"
        ], 
        [
            "none"
        ]
    ], 
    "ARG_PAIR": [
        [
            "<var>", 
            "ARG_PAIR_END"
        ], 
        [
            "<num>", 
            "ARG_PAIR_END"
        ], 
        [
            "EXP", 
            "ARG_PAIR_END"
        ]
    ], 
    "BODY_COMMA": [
        [
            ",", 
            "BODY"
        ], 
        [
            "e"
        ]
    ], 
    "ARG_LIST": [
        [
            "<var>", 
            "ARG_LIST_END"
        ], 
        [
            "<num>", 
            "ARG_LIST_END"
        ], 
        [
            "EXP", 
            "ARG_LIST_END"
        ]
    ]
}